### ISSUE TITLE
Crashes when put in background or when there's no internet

### ISSUE THREAD

**Issue by Bowserinator** [wtg/Shuttle-Tracker-Android#27]
When there's no internet connection the app instantly crashes, and when put into the background after a while it says app is not responding

**Comment by Gerzer** [comment]
@Bowserinator Thanks for the report! We’ll look into this.

@anugrahaawasthi, could you take a look?

**Comment by anugrahaawasthi** [comment]
@Bowserinator @Gerzer The app crashing with no internet connection is a known issue and we're working on a fix. I'm not exactly sure what would be causing the app to crash after being in the background for a while, we'll definitely be looking into that.
